spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/room-escape
    username: sa
    password:

security:
  jwt:
    token:
      secret-key: learning-test-spring
      expire-length: 3600000

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:tcp://localhost/~/room-escape-test
    username: sa
    password: